from __future__ import annotations

from datetime import datetime, timezone
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field

from .document import BoundingBox


class BaseElement(BaseModel):
    """Fields shared by every extractable object in the system.

    All pipelines produce subclasses of this. The shared schema makes it
    possible to write generic index writers and retrievers.
    """

    object_id: str
    doc_id: str
    source_file: str
    page_number: int
    object_type: str
    bbox: BoundingBox | None = None
    tool_name: str
    tool_version: str
    extraction_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    raw_output_path: str | None = None
    parent_id: str | None = None
    child_ids: list[str] = Field(default_factory=list)
    # Section context — set by pymupdf_structured extractor; None for visual pages
    section_title: str | None = None
    section_path: list[str] = Field(default_factory=list)
    heading_level: int | None = None  # 1-based; only set on Heading elements


class VisualPage(BaseElement):
    """A rendered page image with its visual embedding.

    ColQwen2.5 and similar late-interaction models produce one vector per
    image patch, so the embedding is list[list[float]] (multi-vector).
    Single-vector models wrap their output in a one-element outer list.
    """

    object_type: Literal["visual_page"] = "visual_page"
    image_path: str
    embedding: list[list[float]] | None = None


class TextChunk(BaseElement):
    """A chunk of extracted text with a dense embedding."""

    object_type: Literal["text_chunk"] = "text_chunk"
    content: str
    char_start: int | None = None
    char_end: int | None = None
    embedding: list[float] | None = None


class Table(BaseElement):
    """An extracted table in both markdown and structured row form."""

    object_type: Literal["table"] = "table"
    content: str  # markdown representation for embedding
    rows: list[list[str]] = Field(default_factory=list)
    headers: list[str] = Field(default_factory=list)
    embedding: list[float] | None = None


class Formula(BaseElement):
    """A mathematical formula preserved in LaTeX when possible."""

    object_type: Literal["formula"] = "formula"
    latex: str = ""  # empty when parser found region but couldn't extract LaTeX
    content: str  # plain-text fallback for display
    image_path: str | None = None
    embedding: list[float] | None = None


class Figure(BaseElement):
    """A figure, chart, or diagram with optional VLM description."""

    object_type: Literal["figure"] = "figure"
    image_path: str
    description: str | None = None  # generated by FigureDescriptor
    caption: str | None = None  # extracted from document by parser
    embedding: list[float] | None = None


# Discriminated union — enables Pydantic to deserialize the correct subtype
# from JSON/dict using the `object_type` field as the discriminator.
ExtractedElement = Annotated[
    Union[VisualPage, TextChunk, Table, Formula, Figure],
    Field(discriminator="object_type"),
]
